"""Default configuration for the Bitcart Liquidity Helper.

DO NOT EDIT THIS FILE for operational changes. There are three other
ways to override these defaults (highest precedence first):

  1. The Bitcart admin UI (when running as a plugin).
  2. Environment variables — set `LIQUIDITYHELPER_<NAME>=value` in the
     shell or systemd unit. The `LIQUIDITYHELPER_` prefix is required;
     bare `NAME=value` is ignored (with a stderr warning) so we can't
     accidentally pick up unrelated env vars set by other software
     (e.g. system tools owning generic names like STORE_NAME, LOG_LEVEL).
     Strings, ints, floats, bools (`true`/`false`), and `None` are
     auto-parsed. Works for standalone runs.
  3. A sibling `user_config.py` that imports anything it wants to
     override. See `user_config.py` for the minimal template.

The plugin reads the comment block above EACH setting in this file
and surfaces it as a tooltip in the admin UI. Format conventions:

  # === Section name ===
  #
  # Optional section-level paragraph (the parser ignores this — it's
  # for someone reading the file directly).

  # Description of the setting. May span multiple lines; the parser
  # joins them into one paragraph for the tooltip. Aim for 2-4 lines:
  # what it does, typical values, what breaks if it's misconfigured.
  SETTING_NAME: type = default_value

A blank line MUST separate the description block from earlier content;
the parser only treats the contiguous comment block immediately above
the assignment as that setting's description.
"""

from typing import List, Optional
import os
from os import environ

from common_functions import is_integer, is_float


# Unless otherwise stated, all settings apply per-wallet and BTC amounts
# are in sats.


# =============================================================================
# === Liquidity targets ===
# =============================================================================
#
# How much inbound Lightning liquidity the script should maintain. When
# any of these thresholds is missed, liquidity_check requests a new
# channel (via LSP if AUTOMATIC_CHANNEL_CREATION_ENABLED is False, else
# directly to a peer).

# Always maintain at least this many channels with inbound liquidity.
# Higher than ~5 wastes on-chain fees opening lots of small channels;
# 1 puts all your eggs in one channel and risks total inbound loss if
# that channel goes offline or is unilaterally force-closed. Typical: 2.
MIN_CHANNEL_COUNT: int = 2

# Minimum total inbound liquidity to keep across all channels, in sats.
# When total inbound falls below this, the script requests a new channel.
# Should be at least as large as your typical biggest expected invoice;
# higher values mean fewer channel-open events. Typical: 100_000 (100k).
MIN_INBOUND_LIQUIDITY: int = 100_000

# Require at least ONE channel with this much inbound, in sats. Prevents
# the "MIN_INBOUND_LIQUIDITY satisfied by a hundred tiny channels" failure
# mode — a single large incoming payment needs a big enough single channel
# to flow through. Typical: 50_000 (50k).
MIN_INBOUND_LIQUIDITY_PER_CHANNEL: int = 50_000

# Currently UNUSED — no code path reads MIN_RESERVE_TOTAL today. The
# active on-chain reserve floor is computed by
# `effective_min_reserve_onchain()` from MIN_RESERVE_ONCHAIN (LSP mode)
# or the AUTOMATIC_* constants (automatic mode); see those settings.
# Kept here as a placeholder for a future per-wallet total-reserve
# enforcement layer. Don't rely on it for current behavior.
MIN_RESERVE_TOTAL: int = 20_000

# Sats kept specifically on-chain, never sent to cashout, available for
# opening a new LSP channel if liquidity gets tight. Combined with the
# 6-month LSP-quote high-water mark to form the effective on-chain
# reserve floor. Set this to your wallet's worst-case LSP fee.
# Typical: 10_000.
MIN_RESERVE_ONCHAIN: int = 10_000

# Per-channel on-chain buffer kept aside so each channel can be
# force-closed if its peer disappears (force-closes have a CSV-delayed
# sweep transaction whose on-chain fee comes from your wallet).
# Multiplied by the channel count to size the reserve. Typical: 500.
CHANNEL_ONCHAIN_BUFFER: int = 500


# =============================================================================
# === Cashout settings ===
# =============================================================================
#
# Where collected revenue goes. Each tick the script attempts an LN
# cashout (if enabled) and an on-chain cashout (if there's any on-chain
# revenue). If LN cashouts have been failing for
# CASHOUT_SWITCH_TO_ONCHAIN_AFTER_X_DAYS days, the script logs a
# stranded-funds warning and (when LOOP_OUT_ENABLED is True) drains the
# channels to on-chain via submarine swap.

# Enable LN-based cashouts. When True, each tick tries to send funds
# above the channel reserve to CASHOUT_LIGHTNING_ADDRESS. Set False
# only if you've moved entirely to on-chain or are diagnosing LN issues.
ENABLE_CASHOUT_LN: bool = True

# Enable on-chain cashouts. When True, on-chain revenue above the
# reserve floor is swept each tick to CASHOUT_ONCHAIN. Off by default
# because most operators prefer to keep funds flowing through LN.
ENABLE_CASHOUT_ONCHAIN: bool = False

# Prefer on-chain over LN even when LN is healthy. Forces every cashout
# attempt to the on-chain rail and triggers a loop-out drain of any
# accumulating LN balance. Use when you've decided LN custody isn't for
# you and want everything pulled to on-chain.
#
# If PREFER_LN_CASHOUT is also True, PREFER_LN_CASHOUT wins and this
# setting has no effect — the two are opposites and can't both apply.
PREFER_CASHOUT_ONCHAIN: bool = False

# Force all cashouts onto the Lightning rail. When True, on-chain revenue
# that would normally be swept to CASHOUT_ONCHAIN is instead used to
# open a NEW Lightning channel to a node we don't already have a channel
# with (picked by the same gossip-derived ranking the rest of the script
# uses). The LN-balance leg continues to sweep to
# CASHOUT_LIGHTNING_ADDRESS unchanged.
#
# Trade-off: if the amount currently eligible for cashout is below the
# minimum Lightning channel size (MIN_CHANNEL_SIZE_IN_SATS), the cashout
# is delayed until enough accumulates to open a channel. The benefit
# is automatic inbound-liquidity acquisition from a diverse set of
# nodes — every cashout-sized batch of on-chain revenue becomes a new
# routing partner — instead of paying out to a single external address.
#
# Works in both automatic and LSP modes: regardless of
# AUTOMATIC_CHANNEL_CREATION_ENABLED, this path always uses automatic-mode
# node selection so we control which peer we open to.
#
# Wins over PREFER_CASHOUT_ONCHAIN if both are True.
PREFER_LN_CASHOUT: bool = False

# Lightning nodes you control, in `pubkey@host:port` URI format.
# `host` can be an IPv4 address, IPv6 address (wrap in `[]`), or
# a v3 onion hostname. Multiple entries can be added — they're tried
# in the order listed.
#
# Purpose: keep your cashout fees as low as possible by sending funds
# DIRECTLY to your own node instead of routing through the public LN
# graph to a third-party Lightning Address. **These nodes do NOT need
# to be online 24/7** — a phone wallet, an occasional laptop, a Zeus
# remote-control node, etc. all work. The script just retries on each
# tick until the peer is reachable.
#
# WARNING: any node listed here that is NOT online when a customer
# pays a Bitcart invoice with Lightning may cause that payment to
# fail. The public Lightning graph treats announced channels as
# routable; if customers' payments try to route through a channel
# whose far end is offline, those payments fail at the offline hop
# and your customer sees a "no route" error at checkout. This is why
# OWN_LIGHTNING_NODES_ANNOUNCE_CHANNELS (below) defaults to False —
# new channels opened to these peers are PRIVATE (unannounced) by
# default so the public graph never tries to route through them.
# If you DO announce these channels and your peer goes offline, you
# WILL lose customer payments. Only announce when you're sure the
# node is reliably reachable.
#
# What changes when a channel exists to a peer in this list:
#
#   - On-chain → LN cashouts (PREFER_LN_CASHOUT=True): instead of
#     opening a channel to a random peer + paying an invoice, the
#     script opens a channel directly to one of these nodes with
#     `push_sat` set to ~98% of channel capacity. Cashout amount lands
#     on YOUR node in one atomic on-chain operation, zero LN fees.
#
#   - LN → LN cashouts: existing local balance in channels to these
#     peers is keysent BACK to the peer (no invoice round-trip, no
#     LN routing fees beyond the direct hop). Treated as a normal LN
#     cashout for accounting / fees / dashboard. If your node rejects
#     the keysend (LND's --accept-keysend is OFF by default), the
#     engine automatically retries via AMP (spontaneous AMP payment,
#     accepted by LND with --accept-amp which IS on by default in
#     recent versions, plus CLN/LDK/most mobile wallets). For maximum
#     compatibility, enable BOTH on your destination node — the
#     engine prefers keysend (slightly cheaper protocol overhead) and
#     only falls back when keysend is rejected.
#
#   - Channel audit: these channels are SKIPPED. We assume your node
#     may be offline / on a phone / on tor — audit metrics computed
#     against an intermittently-reachable peer are noise.
#
#   - Automatic closure: NEVER. These channels are exempt from every
#     automatic close path (audit failure, force-close escalation,
#     etc.). Operator-initiated closes via lncli/UI still work.
#
#   - Inbound liquidity counting: these channels do NOT count toward
#     MIN_INBOUND_LIQUIDITY or MIN_CHANNEL_COUNT. The script assumes
#     they can't reliably route incoming customer payments (since the
#     peer may be offline). LSP channels are still opened as usual to
#     provide routable inbound capacity.
#
# Fallback chain (on-chain → LN cashout): tries each entry in order.
# If one is offline or refuses the channel, moves to the next. If ALL
# entries fail, falls back to the random-peer channel-open path
# (which then cashes out via the existing CASHOUT_LIGHTNING_ADDRESS).
#
# Example: ["02abcd...@1.2.3.4:9735", "03ffee...@xyz.onion:9735"]
OWN_LIGHTNING_NODES: List[str] = []

# Whether new channels opened to OWN_LIGHTNING_NODES peers should be
# announced to the public Lightning graph.
#
# Default False (private/unannounced) because the typical OWN node is
# a mobile wallet, laptop, or otherwise not-always-online machine.
# Announced channels invite the public graph to route customer
# payments through them; an announced channel whose far end is offline
# turns "customer pays your store" into "customer sees 'no route'".
#
# Set True ONLY if the listed nodes are reliably online (a 24/7 home
# server, a hosted node, etc.). When True, NEW channels opened by the
# direct-channel cashout path are public/announced and can participate
# in routing.
#
# Existing channels keep whatever announcement status they had at
# open time — this toggle only affects NEWLY opened channels.
OWN_LIGHTNING_NODES_ANNOUNCE_CHANNELS: bool = False

# Smallest LN cashout the script will send, in sats. Below this it
# skips the attempt (network fees would dominate). Strike's minimum is
# 100 sats. Raise if you want fewer, larger payouts. Typical: 150.
MIN_LN_CASHOUT_IN_SATS: int = 150

# Lightning Address the LN leg cashes out to. Format `name@host`. Can
# be a custodian (Strike, CoinOS) or a self-hosted address. Required
# for ENABLE_CASHOUT_LN. Intentionally unset by default so a fresh
# install can't accidentally sweep funds to a placeholder address —
# the operator must set this to an address they control before
# enabling LN cashouts.
CASHOUT_LIGHTNING_ADDRESS: Optional[str] = None

# On-chain Bitcoin address for cashouts and (if LOOP_OUT_ENABLED) for
# loop-out drain output. Bech32 / P2TR / P2WPKH all accepted. Required
# when ENABLE_CASHOUT_ONCHAIN=True OR PREFER_CASHOUT_ONCHAIN=True;
# otherwise optional.
CASHOUT_ONCHAIN: Optional[str] = None

# Smallest on-chain payment the script will broadcast, in sats. Gates
# the on-chain cashout sweep AND the on-chain dev-fee + referral-fee
# fallback paths. Below this the tx fees would dominate the payout —
# fees accumulate until the threshold is reached, then go out in one
# tx. Raise to batch revenue/fees into larger, cheaper-per-sat sweeps.
# Typical: 25_000.
MIN_ONCHAIN_CASHOUT: int = 25_000

# If LN cashouts have been failing for this many days, prefer on-chain
# for cashouts on the next tick and (if LOOP_OUT_ENABLED is True) drain
# channels via submarine swap. Set to None to disable the staleness
# fallback entirely. Typical: 30.
CASHOUT_SWITCH_TO_ONCHAIN_AFTER_X_DAYS: Optional[int] = 30


# =============================================================================
# === Developer fee ===
# =============================================================================
#
# The script charges a percentage of revenue as a fee, paid to a
# Lightning Address (LN) or on-chain address (fallback). Per the
# license, the fee component is required — see USE_POLICY.md.

# Developer fee rate as a fraction of revenue. 0.02 = 2%. Network fees
# (LN routing, on-chain miner fees) for the fee payment itself ARE
# deducted from this — if you spend 0.5% on network fees, the net
# fee paid is 1.5%. Required by the license to remain at or above the
# default. Typical: 0.02 (2%).
FEE_AMOUNT: float = 0.02

# Lightning Address to send the developer fee to. Default points at
# the BareBits fee address; don't change unless you've cleared an
# alternative arrangement.
LN_FEE_DEST: str = "fees@getbarebits.com"

# Identifier sent as the LUD-12 `comment` on LNURL fee/referral
# callbacks, formatted as `storeid:<value>`. Only delivered when the
# recipient advertises `commentAllowed > 0`; silently dropped otherwise.
# Used by the receiving endpoint to attribute the incoming payment to
# your deployment when many operators send to the same Lightning
# Address. Plain ASCII recommended. Typical: "default".
BB_STOREID: str = "default"

# On-chain destination for the developer fee. Used when LN fee
# payments have been failing for FEE_SWITCH_TO_ONCHAIN_AFTER_X_DAYS or
# when FORCE_FEE_ONCHAIN_INSTEAD_OF_LN is True. Default points at the
# BareBits on-chain fee address.
ONCHAIN_FEE_DEST: str = "bc1q586um24k7zr6swxqny5qqgqn8xt43pk4xeeg9g"

# Minimum sats accumulated before a fee payment is sent. Smaller fee
# payments are deferred until the accumulator crosses this threshold —
# avoids spending more on network fees than the fee itself is worth.
# Typical: 150.
MIN_FEE_OUT: int = 150

# Master switch for fee payments. Setting this to False means NO fees
# ever leave your wallet, which violates the license. Don't disable
# this in production; reserved for testing.
ENABLE_FEE_SENDING: bool = True

# Use LN as the primary fee-payment rail. When False (or when LN is
# stale), fees go on-chain instead. Most operators leave this True.
ENABLE_FEE_SENDING_LN: bool = True

# Calculate fees against LN-revenue invoices. Set False only if you've
# negotiated an exception for LN volume. Default True.
CHARGE_FEE_FOR_LN_TRANSACTIONS: bool = True

# Calculate fees against on-chain revenue invoices. Default True;
# same caveat as above.
CHARGE_FEE_FOR_ONCHAIN_TRANSACTIONS: bool = True

# Subtract on-chain network fees (channel opens, swaps, LSP fees,
# cashout txs) from the developer fee. Net effect: you pay 2% TOTAL,
# the developer share shrinks as network costs rise. Default True
# (matches the license's "net 2%" promise).
FEES_PAID_INCLUDES_ONCHAIN_NETWORK_FEES: bool = True

# Subtract LN routing fees (the small percentage paid to nodes that
# routed your fee payment) from the developer fee. Default True.
FEES_PAID_INCLUDES_LN_NETWORK_FEES: bool = True

# Start charging fees only on revenue earned on/after this date.
# Format YYYY/MM/DD. Useful if you ran the script before fee tracking
# and don't want retroactive charges. Default well in the past so all
# revenue counts.
FEE_START_DATE: Optional[str] = "1999/11/30"

# Don't charge a fee on the first X sats of revenue (a "free tier").
# Counted across the script's lifetime, not per period. Typical: 0.
FEE_START_REVENUE: int = 0

# If LN fee payments have been failing for this many days, prefer
# on-chain for the dev fee on the next tick. Same shape as the cashout
# version. Set to None to disable. Typical: 30.
FEE_SWITCH_TO_ONCHAIN_AFTER_X_DAYS: Optional[int] = 30


# =============================================================================
# === Referral fee ===
# =============================================================================
#
# Optional flat fee on top of the developer fee, paid to a referrer
# (typically a whitelabel distributor). Customer pays up to
# (FEE_AMOUNT + REFERRAL_FEE_AMOUNT) of revenue. Set REFERRAL_FEE_AMOUNT
# to 0.0 to disable.

# Referral fee rate, additive on top of FEE_AMOUNT. 0.02 = 2% additional.
# Unlike the developer fee, network fees are NOT deducted from this —
# the referrer gets their full configured percentage. Set 0.0 (default)
# if there's no referral arrangement.
REFERRAL_FEE_AMOUNT: float = 0.0

# Lightning Address for the referral payment. Required when
# REFERRAL_FEE_AMOUNT > 0; with this unset the referral payment is
# logged and skipped.
REFERRAL_FEE_DEST: Optional[str] = None

# On-chain Bitcoin address for the referral. Used when LN referrals
# have been failing for REFERRAL_SWITCH_TO_ONCHAIN_AFTER_X_DAYS or
# when FORCE_REFERRAL_ONCHAIN_INSTEAD_OF_LN is True.
REFERRAL_ONCHAIN_DEST: Optional[str] = None

# Transaction label used to identify referral payments in the database.
# Leave at the default unless you have a specific reason to change it.
REFERRAL_PAYOUT_REASON: str = "lnhelper_referral"

# If LN referral payments have been failing for this many days, prefer
# on-chain for referrals on the next tick. Independent of the fee and
# cashout fallback clocks. Typical: 30. Set to None to disable.
REFERRAL_SWITCH_TO_ONCHAIN_AFTER_X_DAYS: Optional[int] = 30


# =============================================================================
# === Liquidity management mode ===
# =============================================================================
#
# Operator-facing top-level switch. The dashboard Settings tab renders a
# single dropdown ("LSP / Automatic / Disabled") that writes through to
# LIQUIDITY_DISABLED + AUTOMATIC_CHANNEL_CREATION_ENABLED (the latter lives
# in the LSP-funded block below). Both flags are hidden from the
# expansion-panel UI so the dropdown is the only authoritative entry
# point; they remain valid settings for env-var / user_config.py
# overrides.

# When True the entire tick loop is paused: run_tick_loop skips its
# call to main() each iteration and sleeps until either the operator
# flips this back to False or the plugin shuts down. Cashouts, fee
# payments, channel creation, topup notifications — everything in
# main() is gated by this. Dashboard endpoints (liquidity stats,
# settings, logs) continue to serve normally so the operator can
# diagnose and re-enable. Default True (engine paused) so a fresh
# install never spends operator funds without an explicit opt-in via
# the dashboard Settings dropdown.
LIQUIDITY_DISABLED: bool = True


# =============================================================================
# === LSP-funded inbound liquidity ===
# =============================================================================
#
# When AUTOMATIC_CHANNEL_CREATION_ENABLED is False (the default), the
# script delegates channel creation to an LSP via the LSPS1 protocol.
# Quotes are pulled from Zeus (lsps1.lnolymp.us) and Megalithic
# (megalithic.me); the cheaper one wins, with a slight Zeus preference
# on near-ties. The on-chain invoice for the LSP fee is paid from your
# wallet's on-chain balance.

# False (default) = delegate channel creation to an LSP via LSPS1.
# True = the script opens channels directly to peers it selects from a
# local candidate database, populated daily by querying your own LND
# node's gossip graph (legacy "pick your own peers" behavior — still
# fully automated, no operator interaction required). Most operators
# should leave this False; LSPs handle the operational pain (route
# reliability, channel-policy tuning) for a small one-time fee. When
# False, the daily gossip pull is skipped entirely — there's no need
# to maintain a candidate list when channel creation is delegated.
AUTOMATIC_CHANNEL_CREATION_ENABLED: bool = False

# Channel size requested from the LSP, in sats. This is your INBOUND
# liquidity per channel — the LSP funds their side, you pay the fee.
# Higher means fewer, larger channels (cheaper per sat of inbound).
# Cap at what you can actually use; idle inbound liquidity does
# nothing for you. Typical: 150_000 (150k).
LSP_CHANNEL_SIZE_SAT: int = 150_000

# Channel lease length in blocks. Channels naturally lapse at the end
# of the lease (the LSP can close them); liquidity_check then requests
# a fresh one. Zeus caps at 13_000 (~90 days) and Megalithic at
# 13_140 — 13_000 is the safe upper bound for both.
LSP_CHANNEL_EXPIRY_BLOCKS: int = 13_000

# Don't even ask an LSP for a quote when on-chain balance is below
# this — no realistic chance of paying any LSP fee. Typical: 1_000.
LSP_MIN_ONCHAIN_FOR_QUOTE_SAT: int = 1_000

# Throttle: at most ONE quote per LSP per wallet per this many hours.
# Each create_order registers a real (abandonable) order on the LSP's
# side; we don't want to spam them. Typical: 24.
LSP_QUOTE_THROTTLE_HOURS: int = 24

# Cap on the dynamic on-chain reserve floor. The effective reserve is
# max(MIN_RESERVE_ONCHAIN, recent LSP price peak), but never above
# this cap. Prevents a freak high quote from locking up the wallet
# indefinitely. Typical: 50_000.
LSP_RESERVE_CAP_SAT: int = 50_000

# Reject LSP quotes whose fee exceeds this fraction of the channel
# size. 0.01 = 1%. A 150_000-sat channel rejects any quote above
# 1500 sat. Raise to 0.05 (5%) if you want more leniency, or 1.0 to
# effectively disable. Also applied retroactively when computing the
# reserve floor. Typical: 0.01.
LSP_MAX_FEE_PERCENT: float = 0.01

# Auto-peer with each LSP's node URI at startup. LSPS1 requires LND
# to be peered before create_order is accepted. Throttled to once per
# day per wallet per LSP. Leave True unless you have a specific
# reason to manually manage peering.
LSP_AUTO_PEER: bool = True


# =============================================================================
# === Automatic-mode reserves ===
# =============================================================================
#
# Only consulted when AUTOMATIC_CHANNEL_CREATION_ENABLED=True. In LSP mode
# the on-chain reserve tracks recent LSP quotes (the LSP-funded inbound
# liquidity block above); in automatic mode the script pays directly for
# channel opens plus a loop-out to recover the local side as on-chain
# inbound. These constants estimate that cost.
#
# The automatic-mode reserve formula is:
#   target_liquidity
#     + MIN_CHANNEL_COUNT * AUTOMATIC_CHANNEL_OPEN_FEE_ESTIMATE_SAT * 2
#     + target_liquidity * AUTOMATIC_LIQUIDITY_LOOPOUT_FEE_PERCENT
#     + AUTOMATIC_RESERVE_SAFETY_SAT
# where target_liquidity = max(MIN_INBOUND_LIQUIDITY,
#                              MIN_INBOUND_LIQUIDITY_PER_CHANNEL * MIN_CHANNEL_COUNT).

# Per-channel on-chain fee estimate for opening (and later closing) a
# channel in automatic-creation mode. The formula multiplies this by
# (MIN_CHANNEL_COUNT * 2) to cover one open and one close per channel.
# Default 1000 sat — conservative for a low-priority funding tx.
# Raise it if you typically open at higher fee targets.
AUTOMATIC_CHANNEL_OPEN_FEE_ESTIMATE_SAT: int = 1_000

# Loop-out cost as a fraction of target inbound liquidity. The automatic-
# mode reserve assumes the script will fund inbound liquidity by opening
# channels and looping the local side back out to on-chain;
# this captures the swap-fee portion of that operation. 0.01 = 1%.
AUTOMATIC_LIQUIDITY_LOOPOUT_FEE_PERCENT: float = 0.01

# Safety buffer added on top of the automatic-mode reserve floor. Also
# acts as a hysteresis zone for low-on-chain warnings: if the wallet
# is within this many sats of the reserve floor, top-up warnings (log
# + SMTP) are suppressed. Action gates (refuse to open new channels,
# refuse to move on-chain to LN) still fire — the safety zone is only
# about not pestering the operator inside small fluctuations.
AUTOMATIC_RESERVE_SAFETY_SAT: int = 1_000


# =============================================================================
# === LND fee controls ===
# =============================================================================
#
# Per-tx miner-fee + per-payment routing-fee knobs for the LND-direct
# paths (SendCoins, SendPaymentSync, OpenChannelSync, CloseChannel).
# All paths previously inherited LND's hardcoded defaults or used
# placeholder values that were fine for regtest but wrong on mainnet.
#
# Defaults below are tuned for mainnet at typical congestion. The
# direct-channel cashout path uses a higher (cheaper) target_conf
# because channel opens are less urgent than payouts; cooperative
# closes use the standard 6-block target with a hard ceiling so a
# fee-estimator spike can't burn the channel's local balance.

# Block-confirmation target for on-chain SendCoins payments OTHER
# than cashouts (developer fee, referral fee, LSP order payment, etc).
# LND queries its fee estimator for the sat/vbyte rate that targets
# confirmation within N blocks. 6 = LND's own internal default
# (~30-60 min on mainnet); raise for cheaper but slower confirmation,
# lower for faster but more expensive. Cashouts use their own
# (slower, cheaper) target via LND_CASHOUT_TARGET_CONF below.
LND_ONCHAIN_TARGET_CONF: int = 6

# Block-confirmation target for on-chain cashout payments
# (CASHOUT_ONCHAIN sends labeled `lnhelper_cashout`). Set high
# because cashouts are not customer-facing urgent — the operator's
# revenue is already sitting in the wallet and the cashout just
# moves it to their preferred destination. A 144-block (~24-hour)
# target typically pays the very lowest sat/vbyte rate LND's fee
# estimator advertises, saving ~5-10x vs the 6-block default during
# normal mainnet conditions and ~20-50x during congestion. The
# trade-off is that the cashout may sit unconfirmed for up to a
# day, which is fine for routine wallet-drain operations.
LND_CASHOUT_TARGET_CONF: int = 144

# Explicit sat/vbyte override for on-chain SendCoins payments. When
# non-zero this wins over LND_ONCHAIN_TARGET_CONF. Use only when you
# need to force a specific feerate (e.g. operator manually picked a
# rate from mempool.space during a congestion spike). 0 = let
# LND_ONCHAIN_TARGET_CONF + LND's fee estimator decide.
LND_ONCHAIN_FEE_RATE_SAT_PER_VBYTE: int = 0

# Block-confirmation target for direct-channel cashouts
# (OpenChannelSync with push_sat). Channel opens are less urgent than
# regular payouts — a 12-block target halves the typical fee vs the
# 6-block default at the cost of one extra hour to confirmation,
# which doesn't matter because the LN funds become spendable only
# after 6 confs anyway.
LND_CHANNEL_OPEN_TARGET_CONF: int = 12

# Block-confirmation target for cooperative channel closes.
# Cooperative closes typically settle within hours; we want them
# confirmed promptly so the local balance becomes spendable, but
# they're not customer-facing urgent.
LND_CHANNEL_CLOSE_TARGET_CONF: int = 6

# Hard ceiling on the close tx's per-vbyte feerate. LND's fee
# estimator can spike during mempool congestion (multi-thousand
# sat/vbyte during 2024 inscription seasons); without a ceiling a
# close fee could eat a meaningful fraction of the channel's local
# balance. 50 sat/vbyte is plenty for "fast" under typical mainnet
# conditions and caps the worst case at ~25k sats per close on a
# 500 vbyte tx.
LND_CHANNEL_CLOSE_MAX_FEE_SAT_PER_VBYTE: int = 50

# Maximum CSV delay (in blocks) we'll allow on OUR local commitment
# output when opening a new channel. If WE force-close the channel,
# our `to_local` funds are CSV-locked by this many blocks before we
# can spend them. The peer can negotiate something HIGHER at channel
# open; we refuse and the open fails. Lower = faster recovery on
# force-close. Trade-off: lower CSV = less protection against a
# revoked-state attack (an attacker who steals our state during the
# CSV window could publish it). With anchor channels + a watchtower
# this risk is mitigated.
#
# 0 = don't override (let LND's daemon-level --max-local-csv-delay
# decide, default 2016 ~ 14 days). Setting this lower than 2016
# REQUIRES the remote peer to also configure a low CSV auto-pick;
# otherwise their auto-pick (typically 600 for typical channel sizes)
# will be > our cap and the OpenChannel fails. The plugin cannot
# coordinate this on its own — operators of OWN_LIGHTNING_NODES who
# want a sub-2016 cap must also set --max-local-csv-delay on the
# OWN node, and LSP channels inherit the LSP's CSV policy regardless.
# Default 0 to avoid breaking opens when the peer ships LND defaults.
#
# Only applies to channels OPENED BY US — peer-funded channels and
# LSP-funded inbound channels are negotiated by the other side and
# inherit their CSV policy. See move_onchain_to_ln and
# _attempt_direct_channel_cashout_to_own_node for the wire-through.
LND_MAX_LOCAL_CSV_BLOCKS: int = 0

# CSV delay (in blocks) WE impose on the REMOTE peer's `to_local`
# output. If THEY force-close, their funds are CSV-locked by this
# many blocks before they can spend them. Higher = more protection
# for us against the peer publishing a revoked state.
#
# 0 = let LND auto-scale by channel size (LND's default behavior;
# typically 144-2016 blocks depending on size). Operators usually
# leave this at 0 — lowering it weakens our cheating-protection
# without gaining us anything (the peer's funds being locked
# doesn't speed up our wallet recovery).
LND_REMOTE_CSV_DELAY_BLOCKS: int = 0

# Maximum LN routing fee (as a fraction of the payment amount) for
# every outgoing LN payment except the AMP fallback (which has its
# own cap baked in). Defends against a poorly-routed payment paying
# surprising fees — without this, LND's default fee_limit applies,
# which has shifted across LND versions.
# 0.02 = 2%, matches the engine's developer fee rate so a worst-case
# fee payment can't itself cost more than the fee being paid.
LN_PAYMENT_FEE_LIMIT_PERCENT: float = 0.02

# Absolute floor for the LN routing-fee cap. Used when a payment is
# so small that PCT × amount rounds to 0 (which LND's path-finder
# rejects). 50 sats covers a 5-hop route at 10 sat/hop.
LN_PAYMENT_FEE_LIMIT_MIN_SAT: int = 50


# =============================================================================
# === Channel rebalancing ===
# =============================================================================
#
# Periodic small circular rebalances that quietly cycle sats between
# channels to keep them in use. The point is to discourage peers from
# closing channels because they look idle / unbalanced — a tiny steady
# drip of traffic signals "this channel is active." Also helps
# maintain inbound capacity for customer payments by pushing sats out
# of over-full channels into emptier ones.
#
# Each tick (before fee payment and cashouts) the engine checks
# whether today's fee budget is still available and, if so, attempts
# a self-payment from the most over-full channel through the LN graph
# back into the most empty channel. The amount auto-adjusts via
# binary-halving until the routing fee fits within the budget.
#
# Sats *received* via a rebalance do NOT count as revenue — rebalance
# invoices are created via LND gRPC directly (not Bitcart's invoice
# store), so they never enter the revenue-walk. Fees paid for
# rebalances DO count as network fees and are credited toward the 2%
# developer-fee cap (same treatment as cashout / fee-payment fees).

# Yearly fee budget for automatic channel rebalancing. Daily allowance
# = total / 365. Unused daily allowance rolls over (the engine tracks
# the first-attempt date and computes available = daily × days_active
# − total_fees_spent). 0 disables the rebalancer entirely.
#
# Default 3000 sats/year (~8.2 sats/day) is intentionally small —
# the goal is "channel keep-alive" signaling, not active liquidity
# management. Operators wanting more aggressive rebalancing should
# raise this; tests show ~5-10× this for materially-frequent
# rebalances on typical mainnet fee conditions.
REBALANCE_YEARLY_BUDGET_SAT: int = 3000

# Per-channel safety reserve in sats. The rebalancer will never push
# a channel's local balance below this amount, and never attempt to
# move less than this amount (HTLCs below this are likely dust and
# won't route reliably). Doubles as the floor in the binary-halving
# amount search — when the halving probe drops below this floor with
# no viable fee, we move on to the next channel pair.
REBALANCE_MIN_CHANNEL_BUFFER_SAT: int = 1000


# =============================================================================
# === Submarine swaps (LN → on-chain) ===
# =============================================================================
#
# Lightning Labs `loop` daemon integration. Used to drain LN balance
# to on-chain when LN cashouts are stuck. Requires a running `loopd`
# instance per LND wallet; see DESIGN.md for setup. Off by default
# because of the external infrastructure requirement.

# Master gate for actually firing swap-outs. False (default) means
# liquidityhelper detects candidate channels and logs them but never
# initiates a swap. Flip to True once you have a vetted loopd setup.
LOOP_OUT_ENABLED: bool = False

# A channel becomes a loop-out candidate when its local_balance is
# above this. Lower = more aggressive draining. Typical: 20_000.
LOOP_OUT_TRIGGER_LOCAL_BALANCE_SAT: int = 20_000

# Reject swap quotes with total fee above this flat sat amount.
# Combined with MAX_SWAP_PERCENT as a logical OR; either threshold
# triggers a reject. Typical: 50_000.
MAX_SWAP_FLAT: int = 50_000

# Reject swap quotes with fee/amount ratio above this fraction.
# 0.01 = 1%. Typical: 0.01.
MAX_SWAP_PERCENT: float = 0.01

# Minimum excess LN balance before a drain swap fires, in sats. Below
# this, no swap — fees would dominate. Typical: 500_000 (500k).
LN_DRAIN_MIN_SWAP_SAT: int = 500_000

# Hard cap per single drain swap, in sats. loopserver's default per-
# swap maximum. Multiple ticks drain larger excesses incrementally.
# Typical: 5_000_000 (5M).
LN_DRAIN_MAX_PER_TICK_SAT: int = 5_000_000

# loopd Bitcoin network. Per Lightning Labs' `loopd/daemon.go`:
#   mainnet → swap.lightning.today:11010 (built-in default)
#   testnet → test.swap.lightning.today:11010 (built-in default)
#   signet  → signet.swap.lightning.today:11010 (built-in default)
#   regtest → no built-in server; you MUST set LOOPD_SERVER_HOST.
#   simnet  → same as regtest.
# Must match the LND wallet's network or loopd and LND will refuse to
# interoperate (chain-hash mismatch). The script enforces this at
# loopd startup by comparing against the wallet's GetInfo.
LOOPD_NETWORK: str = "mainnet"

# Override loopd's swap server URL. Leave empty to use the
# network-appropriate Lightning Labs default (see LOOPD_NETWORK).
# REQUIRED on regtest/simnet — loopd has no public server there and
# will refuse to start. Format: "host:port" e.g. "127.0.0.1:11010".
LOOPD_SERVER_HOST: str = ""

# Disable TLS when connecting to the swap server. Only meaningful for
# regtest/CI setups where a self-hosted loopserver runs without TLS.
# Production paths (mainnet/testnet/signet) always use TLS regardless
# of this setting — the Lightning Labs servers serve TLS only.
LOOPD_SERVER_NOTLS: bool = False


# =============================================================================
# === Autoloop (Lightning Labs autoloop) ===
# =============================================================================
#
# When AUTOLOOP_ENABLED=True, liquidityhelper pushes these values into
# each LND wallet's loopd via SetLiquidityParams at startup. Loopd
# then manages outbound liquidity autonomously within these bounds.
# Field names mirror loopd's LiquidityParameters proto. Off by default.

# Enable autoloop. Requires LOOP_OUT_ENABLED to also be True and a
# running loopd. When enabled, loopd handles outbound liquidity
# rebalancing on its own; this script just configures it.
AUTOLOOP_ENABLED: bool = False

# Destination address for autoloop's swap output. Three modes:
#   - None (default): loopd asks LND for a fresh address per swap.
#     Best privacy, but funds remain in LND's wallet.
#   - A single Bitcoin address: every swap reuses it. Easy but
#     clusters all outputs on-chain.
#   - Use AUTOLOOP_ACCOUNT instead for xpub-derived per-swap
#     addresses to a cold wallet.
AUTOLOOP_DEST_ADDRESS: Optional[str] = None

# Watch-only LND account name (import via `lncli wallet accounts
# import <xpub> <name> --address_type=p2tr`). When set, autoloop
# derives a fresh on-chain address from that xpub for each swap —
# funds land in addresses YOU control via the corresponding seed.
# Best privacy + custody.
AUTOLOOP_ACCOUNT: Optional[str] = None

# Address type derived from the xpub. Only "p2tr" (taproot) is
# supported by loopd today. Leave at default.
AUTOLOOP_ACCOUNT_ADDR_TYPE: str = "p2tr"

# Autoloop is allowed to spend at most this many sats in fees per
# refresh period (see AUTOLOOP_BUDGET_REFRESH_PERIOD_SEC). Acts as a
# safety net against runaway swap costs. Typical: 100_000.
AUTOLOOP_BUDGET_SAT: int = 100_000

# How often the budget resets, in seconds. 604_800 = 1 week.
AUTOLOOP_BUDGET_REFRESH_PERIOD_SEC: int = 604_800

# Minimum per-swap amount autoloop will initiate, in sats.
# Typical: 250_000.
AUTOLOOP_MIN_SWAP_AMOUNT_SAT: int = 250_000

# Maximum per-swap amount autoloop will initiate, in sats.
# Typical: 5_000_000 (5M, loopserver default).
AUTOLOOP_MAX_SWAP_AMOUNT_SAT: int = 5_000_000

# Maximum concurrent autoloop swaps. Higher values give faster
# rebalancing but more concurrent loopd activity. Typical: 1.
AUTOLOOP_MAX_IN_FLIGHT: int = 1

# Overall fee cap in parts-per-million of the swap amount. If
# non-zero, this OVERRIDES the granular fee knobs below. 0 = use the
# granular controls. Typical: 0 (use granular).
AUTOLOOP_FEE_PPM: int = 0

# Max swap fee paid to the loopserver, in ppm. 5_000 = 0.5%.
AUTOLOOP_MAX_SWAP_FEE_PPM: int = 5_000

# Max LN routing fee for the swap, in ppm. 5_000 = 0.5%.
AUTOLOOP_MAX_ROUTING_FEE_PPM: int = 5_000

# Max LN routing fee for the prepay portion of the swap, in ppm.
# 50_000 = 5%. Higher than the main swap because the prepay is small
# and routing it can disproportionately cost. Typical: 50_000.
AUTOLOOP_MAX_PREPAY_ROUTING_FEE_PPM: int = 50_000

# Hard sat cap on the prepay portion. Typical: 100_000.
AUTOLOOP_MAX_PREPAY_SAT: int = 100_000

# Max miner fee for the on-chain HTLC sweep, in sats. Typical: 15_000.
AUTOLOOP_MAX_MINER_FEE_SAT: int = 15_000

# Confirmation target for the on-chain sweep (less-urgent, batchable).
# 100 = ~24h. Typical: 100.
AUTOLOOP_SWEEP_CONF_TARGET: int = 100

# Confirmation target for the HTLC publication. Faster (lower) = more
# expensive. Typical: 6 (~1 hour).
AUTOLOOP_HTLC_CONF_TARGET: int = 6

# Sweep fee rate in sat/vbyte. 0 = use the estimator
# (AUTOLOOP_SWEEP_CONF_TARGET). Set non-zero to override. Typical: 0.
AUTOLOOP_SWEEP_FEE_RATE_SAT_PER_VBYTE: int = 0

# After a failed swap, wait this many seconds before retrying autoloop.
# Default 86_400 (1 day) to avoid hammering loopserver during outages.
AUTOLOOP_FAILURE_BACKOFF_SEC: int = 86_400

# Simplified mode (mutually exclusive with per-channel rules, which
# this script doesn't expose). When True, loopd targets each channel's
# local balance to AUTOLOOP_EASY_LOCAL_TARGET_SAT. Easier but less
# nuanced. Typical: False.
AUTOLOOP_EASY_MODE: bool = False

# Per-channel local balance target for easy mode, in sats. Only
# relevant when AUTOLOOP_EASY_MODE=True.
AUTOLOOP_EASY_LOCAL_TARGET_SAT: int = 0

# Publish swap transactions as fast as possible (higher fee).
# Default False — uses the estimator for normal-pace publishing.
AUTOLOOP_FAST_SWAP_PUBLICATION: bool = False

# List of hex pubkeys easy-autoloop should ignore. Useful for excluding
# a flaky peer from rebalancing without disabling autoloop entirely.
AUTOLOOP_EASY_EXCLUDED_PEERS: List[str] = []


# =============================================================================
# === Notifications (SMTP) ===
# =============================================================================
#
# Email notifications for noteworthy events (channel close, stuck
# funds, etc.). All fields must be set for email to actually fire;
# any single field left as None disables email notifications.

# SMTP server hostname or IP, e.g. "smtp.gmail.com".
SMTP_SERVER: Optional[str] = None

# SMTP server port. 587 for TLS, 465 for SSL, 25 for unencrypted.
SMTP_PORT: Optional[int] = None

# Use STARTTLS. Set True for ports like 587. Mutually exclusive with
# SMTP_SSL.
SMTP_TLS: bool = False

# Use implicit SSL. Set True for port 465. Mutually exclusive with
# SMTP_TLS.
SMTP_SSL: bool = False

# "From" email address — must usually match the authenticated SMTP user.
SMTP_FROM_EMAIL: Optional[str] = None

# Friendly display name shown alongside the "From" address.
SMTP_FROM_NAME: Optional[str] = "LiquidityHelper"

# Destination email address for notifications.
SMTP_TO_EMAIL: Optional[str] = None

# SMTP username (often the same as SMTP_FROM_EMAIL).
SMTP_USERNAME: Optional[str] = None

# SMTP password or app-specific password. NEVER commit this to git;
# set via environment variable or user_config.py outside version control.
SMTP_PASSWORD: Optional[str] = None


# =============================================================================
# === Standalone bootstrap ===
# =============================================================================
#
# Used only for the standalone `python liquidityhelper.py` path. In
# plugin mode the plugin acquires its own bearer token via Bitcart's
# DI container and these are ignored.

# Bitcart API bearer token. Find it in Bitcart at User Profile → API
# keys. Leave None on first run and set ADMIN_EMAIL/ADMIN_PASSWORD
# below — the script will create the admin user + token automatically.
AUTH_TOKEN: Optional[str] = None

# Legacy log-level knob. Kept for backward compatibility but is now a
# no-op: the engine routes file logs at DEBUG and stdout at INFO
# regardless. Adjust handlers in liquidityhelper.py directly if you
# need different thresholds.
LOG_LEVEL: str = "WARNING"

# Name of the Bitcart store created on first run if none exists.
STORE_NAME: str = "mystore"

# Email of the admin user created on first run if Bitcart has no users
# yet. Required for both standalone AND plugin first-boot bootstrap.
ADMIN_EMAIL: Optional[str] = None

# Password of the auto-created admin user. Set via environment variable
# or user_config.py — don't commit it.
ADMIN_PASSWORD: Optional[str] = None


# =============================================================================
# === Debug & operator overrides ===
# =============================================================================
#
# Knobs for testing, diagnostics, or forcing a specific behavior. Most
# of these should be False/None in production; some are useful for
# operators verifying behavior against a real Bitcart instance.

# Dry-run mode: run all logic but DON'T move any actual funds. Logs
# what would have happened. Good for verifying configuration changes
# before letting them touch real money.
DRY_RUN_FUNDS: bool = False

# Run once and exit. Standalone-mode only — the plugin tick loop
# ignores this. Useful for crontab-style scheduling instead of the
# script's own loop. Default False.
SINGLE_RUN: bool = False

# Manual-step debug mode. When True, the main loop does NOT auto-cycle;
# instead it blocks waiting for an explicit "run one tick" trigger.
# The plugin's Logs tab surfaces a button that fires this trigger so
# you can step through the loop one iteration at a time and watch the
# decision stream between iterations. Toggling this back to False
# resumes normal continuous looping on the next tick. Distinct from
# SINGLE_RUN: SINGLE_RUN runs once and EXITS; DEBUG_MODE runs once
# per trigger and KEEPS WAITING for more triggers, so the process
# stays alive (and the HTTP endpoints stay reachable).
DEBUG_MODE: bool = False

# Stop in the Python debugger between each major step (liquidity check,
# fee payment, cashout). Only useful for interactive debugging of the
# script's own flow.
DEBUG_STEPS: bool = False

# Force a specific fee amount in sats for every fee payment, ignoring
# the calculated amount. For testing only.
FORCE_FEE_AMOUNT: Optional[int] = None

# Run the fee-calculation pass even if it was just done. Bypasses
# the daily cadence. For testing.
FORCE_FEE_CHECK: bool = False

# Send fee payment to this specific LN invoice instead of the
# Lightning Address. Overrides FORCE_FEE_AMOUNT (the invoice has its
# own amount). For testing.
FORCE_FEE_INVOICE: Optional[str] = None

# Always send the developer fee on-chain, regardless of LN health.
# Operator override for the recency-based fallback. Useful if your
# LN routing is permanently broken and you just want the fee gone.
FORCE_FEE_ONCHAIN_INSTEAD_OF_LN: Optional[bool] = False

# Same as above but for the referral fee. Independent toggle so you
# can route the dev fee one way and the referral another.
FORCE_REFERRAL_ONCHAIN_INSTEAD_OF_LN: Optional[bool] = False

# Force a specific LN cashout amount in sats, ignoring what's
# actually available. Bypasses the LSP-shortfall holdback. For testing.
FORCE_CASHOUT_AMOUNT_LN: Optional[int] = None

# Force a specific on-chain cashout amount in sats. Same caveats.
FORCE_CASHOUT_AMOUNT_ONCHAIN: Optional[int] = None

# Send LN cashouts to this specific invoice instead of the configured
# Lightning Address. For testing.
FORCE_CASHOUT_INVOICE: Optional[str] = None

# Skip the 30-second startup wait before assuming LN wallets are
# online. Speeds up tests at the cost of occasional first-tick churn.
SKIP_WALLET_DELAY: bool = False


# =============================================================================
# === Internal / legacy (rarely change) ===
# =============================================================================
#
# These are mostly tx labels, protocol minimums, and run-frequency
# knobs that aren't deeply respected anymore. Documented for
# completeness but you almost never want to change them.

# Transaction label for developer-fee payments. Used to identify them
# in payment history; changing it breaks fee-accounting against old txs.
FEE_PAYOUT_REASON = "lnhelper_fee"

# Transaction label for cashout payments. Same caveat as above.
CASHOUT_REASON = "lnhelper_cashout"

# Transaction label for circular-rebalance self-payments. Written to
# LndPaymentLabel on every successful rebalance so the existing
# `list_ln_payments_with_labels` walker sees the payment with this
# label, and `new_calc_invoice_stats` can bucket the routing fee
# into ln_network_fees_paid_for_rebalances_in_sats.
REBALANCE_REASON = "lnhelper_rebalance"

# Transaction label for direct-channel-push cashouts (the
# PREFER_LN_CASHOUT + OWN_LIGHTNING_NODES path that opens a channel
# straight to your own LN node with push_sat). Format is
# `<this constant>:<peer_pubkey>` so the dashboard can render the
# destination column with the actual peer. Surfaced in the dashboard's
# Recent Cashouts table with method="direct_channel".
CASHOUT_DIRECT_CHANNEL_REASON = "lnhelper_cashout_direct"

# Label used for self-topup invoices the script creates to test
# liquidity. Don't change without understanding the topup flow.
TOPUP_NAME = "topupself"

# Label used for BareBits-administered topup invoices (historical).
TOPUP_BAREBITS = "topupbarebits"

# Smallest channel size the protocol/Bitcart allows. 60_000 is the
# Electrum/Bitcart minimum; lower will be rejected by the daemon.
# https://github.com/bitcart/bitcart/blob/master/daemons/btc.py
MIN_CHANNEL_SIZE_IN_SATS = 60_000

# How often (seconds) the liquidity check runs. 1 = every tick. Legacy
# knob: the main tick runs liquidity_check unconditionally now.
RUN_FREQUENCY_LIQUIDITYCHECK: int = 1

# How often (seconds) to recalculate accumulated fees due. 86_400 = once
# per day. Legacy knob: the calculation now runs each tick.
RUN_FREQUENCY_FEE_CALCULATION: int = 86_400

# How often (seconds) to refresh the list of candidate Lightning nodes
# from the developer node-list endpoint. 86_400 = once per day. Only
# relevant in the legacy automatic-channel-open path.
RUN_FREQUENCY_PULL_DEV_NODES: int = 86_400

# Legacy; no longer consulted. Historical default 46_400 seconds
# (~12.9h, not exactly half a day). Payment attempts now happen each
# tick.
RUN_FREQUENCY_FEE_PAYMENT: int = 46_400

# Gossip-readiness gate: the daily LND gossip pull (refresh_lnd_node_database)
# runs only when LND's view of the network is healthy enough to trust.
# A sparse pull (fresh wallet, recently-restarted wallet that hasn't yet
# reabsorbed gossip, neutrino mid-sync) re-computes connectivity metrics
# against an incomplete adjacency and POISONS the candidate node DB.
# The check runs BEFORE upsert; if any signal fails, the pull is skipped
# entirely and the previous-day's candidate data remains in use.
#
# Three signals (all must pass):
#   1. LND.GetInfo.synced_to_graph == True
#   2. engine-tracked observation age >= GOSSIP_MIN_UPTIME_SECONDS
#      (proxy for LND uptime; see note on GOSSIP_MIN_UPTIME_SECONDS below)
#   3. DescribeGraph.nodes count >= GOSSIP_MIN_NODE_COUNT
#      (only enforced on mainnet — testnet/signet/regtest variants have
#      legitimately small graphs and would always fail this check.)
GOSSIP_MIN_NODE_COUNT: int = 250

# Minimum LND-observation age in seconds before the gossip pull will
# trust its view. The engine tracks 'first time we saw a GetInfo
# response from this wallet's LND' as a proxy for uptime (the LND proto
# checked into this repo predates GetInfoResponse.uptime, so we can't
# read it directly). 15 seconds gives the gossip subsystem at least one
# round of peer reconnects; on a process that's been alive for hours
# this clears immediately.
GOSSIP_MIN_UPTIME_SECONDS: int = 15

# Selection-time staleness gate: pick_best_channel_partners refuses to
# return any candidates if the last successful gossip pull is older
# than this many days. Protects against the "haven't pulled in ages
# because LND has been broken and the daily check kept skipping"
# scenario — keeping the stale-but-valid candidates from being used
# for channel opens after they've outlived their reliability window.
GOSSIP_MAX_STALENESS_DAYS: int = 7

# Minimum total channel capacity (sats) a candidate Lightning node must
# have for the legacy automatic-channel-open path to consider it. Filters
# out tiny/test nodes. Typical: 1_000_000 (1M).
NODE_CRITERIA_MINIMUM_CAPACITY: int = 1_000_000

# Minimum number of channels a candidate Lightning node must already
# have for the legacy automatic-channel-open path to consider it. Filters
# out newly-launched nodes. Counts every announced channel, including
# ones the node operator has disabled or stopped gossiping policies
# for — see NODE_CRITERIA_MIN_EFFECTIVE_DEGREE below for the stricter
# "channels that can actually route" floor used at selection time.
# Typical: 10.
NODE_CRITERIA_MINIMUM_CHANNELCOUNT: int = 10

# Minimum number of EFFECTIVE outbound channels a node must have to
# pass the blacklist. An effective channel is one where:
#   - the node's outbound policy is not disabled, AND
#   - the policy has been gossip-updated within the last 14 days.
# A node with 100 announced channels but only 3 effective ones routes
# like a 3-channel node. The raw count above is the cheap pre-filter;
# this is the actual routing-quality gate. Typical: 10.
NODE_CRITERIA_MIN_EFFECTIVE_DEGREE: int = 10

# Minimum number of distinct nodes the candidate must be able to reach
# in 1 OR 2 hops through effective edges. Acts as a connectedness
# proxy: a node with high 2-hop reach can deliver payments to a wide
# slice of the network without needing long routes. Calibrate against
# your actual gossip distribution; values below ~500 usually indicate
# an isolated sub-cluster. Typical: 500.
NODE_CRITERIA_MIN_TWO_HOP_REACH: int = 500

# Granularity (parts-per-million) of the fee-rate bucket used for
# ordering candidates. Default 1000 ppm = 0.10%. Nodes with similar
# fee rates (within one bucket) are differentiated by 2-hop reach;
# nodes in different fee buckets are ordered cheapest-first regardless
# of reach. Lower granularity (e.g. 500) means tighter buckets and
# more fee-rate competition; higher granularity (e.g. 2500) means
# fewer buckets and more emphasis on connectedness. Typical: 1000.
NODE_FEE_BUCKET_PPM: int = 1000

# Maximum acceptable min_htlc_msat for a candidate peer (in millisats).
# Computed as the median of the peer's outbound channel policies. If
# the peer typically refuses to forward HTLCs smaller than this, they
# may block customer payments to your store. Default 75_000 msat =
# 75 sat — peers that won't forward sub-75-sat payments are rejected
# pre-open. Setting this too low (e.g. 1_000 msat = 1 sat) is harmless
# but restrictive; too high (e.g. 1_000_000 msat = 1000 sat) defeats
# the purpose of the filter for a payment-accepting store. Typical:
# 75_000 (= 75 sat).
NODE_CRITERIA_MAX_MIN_HTLC_MSAT: int = 75_000

# Minimum max_htlc_msat a candidate peer should advertise, expressed
# as a fraction of LSP_CHANNEL_SIZE_SAT. 0.5 means the peer must be
# willing to forward at least half the channel size in a single HTLC.
# Too-low max_htlc_msat means the peer is self-throttling — a large
# customer payment in one shot would fail at their hop. Setting to
# 0.0 disables the check entirely. Typical: 0.5.
NODE_CRITERIA_MIN_MAX_HTLC_FRACTION: float = 0.5

# Daily-audit master switch. When True (opt-out default), every open
# channel is re-evaluated daily against five degradation criteria
# (HIGH_FEE_RATE, LOW_EFFECTIVE_DEGREE, LOW_TWO_HOP_REACH, LOW_CAPACITY,
# LOW_OUTBOUND_CAPACITY). 3 consecutive daily failures → cooperative
# close + 180-day blacklist of the peer. Set False to disable audits
# entirely (channels never auto-close regardless of peer degradation).
CHANNEL_AUDIT_ENABLED: bool = True

# Number of consecutive daily-audit failures required before the script
# closes a channel. Provides hysteresis against transient fee-rate
# spikes during peer node restarts or gossip propagation delays.
# Lower = more aggressive (faster reaction, more risk of churn); higher
# = slower (more tolerant of transients, larger window of paying high
# fees before action). Typical: 3.
CHANNEL_AUDIT_CONSECUTIVE_FAILURES_TO_CLOSE: int = 3

# Per-day safety cap on audit-driven closes. Caps the blast radius of
# a graph-pull anomaly that incorrectly flags many peers. Worst case
# at default 1: a 21-channel deployment takes 21 days to drain entirely.
# Real cascading peer-quality problems are rare; the cap mainly protects
# against data anomalies. Typical: 1.
CHANNEL_AUDIT_MAX_CLOSES_PER_DAY: int = 1

# How long (in days) a peer remains audit-blacklisted after we close a
# channel with them for audit failure. During this period the peer is
# rejected by is_node_blacklisted as AUDIT_BLACKLISTED regardless of
# their current metrics. Gives the operator time to evaluate before
# re-engaging with a peer the script has decided to drop. Typical: 180.
CHANNEL_AUDIT_BLACKLIST_DAYS: int = 180

# Master switch for the coop-close retry loop. When True (default,
# opt-out), the script periodically re-issues cooperative close
# requests for channels that we asked to be closed but which haven't
# resolved (peer offline, never signed the closing tx). After
# CHANNEL_COOP_CLOSE_TIMEOUT_DAYS days of failed coop attempts the
# channel is escalated to force close. Set False to study stuck
# closes manually without the script intervening.
CHANNEL_COOP_CLOSE_RETRY_ENABLED: bool = True

# How often (in hours) the retry loop re-issues a coop close for a
# channel whose first close request hasn't resolved. LND doesn't
# auto-retry coop closes — if the peer was offline when we asked,
# the request is dropped on their end and we have to re-issue when
# they come back online. Hourly retries catch peers that pop up
# briefly without spamming LND. Typical: 1.
CHANNEL_COOP_CLOSE_RETRY_INTERVAL_HOURS: int = 1

# Days after the FIRST coop close request before escalating to force
# close. Force closes have a CSV timelock (typically days to weeks
# before our funds are spendable on-chain) which is why we wait this
# long before triggering — gives a flaky-but-occasionally-online peer
# plenty of chances to coop. Typical: 10.
CHANNEL_COOP_CLOSE_TIMEOUT_DAYS: int = 10

# Per-day cap on force closes initiated PER WALLET. Limits blast
# radius of any anomaly that flags many channels for escalation on
# the same day. Per-wallet (not global) so a healthy wallet isn't
# penalized by a sick one's force-close burst. Typical: 1.
CHANNEL_FORCE_CLOSE_MAX_PER_DAY_PER_WALLET: int = 1

# How long (in days) a peer remains blacklisted after we force-close a
# channel with them. Force close means coop close failed for the full
# CHANNEL_COOP_CLOSE_TIMEOUT_DAYS window — the peer was unreachable
# or refused to sign — so we don't re-engage for a long time. 365 days
# is significantly longer than the 180-day audit blacklist because
# force-close is a STRONGER negative signal: the peer wasn't just
# operating a low-quality node, they actively failed to coop with us.
# Independent from CHANNEL_AUDIT_BLACKLIST_DAYS — a peer could have
# both timestamps set, and is_node_blacklisted honors whichever
# expires later. Typical: 365.
CHANNEL_FORCE_CLOSE_BLACKLIST_DAYS: int = 365

# How often (minutes) the per-peer uptime tracker runs. Updates
# recent_uptime_checks / recent_failed_uptime_checks counters per peer
# of any open channel. Previously ran every tick (~90s) which made
# the threshold math nonsensical at scale; 10 minutes gives ~26,000
# samples per peer per 6-month window — enough for the failure-ratio
# gate below to be statistically meaningful. Operator-tunable; lower
# values mean more samples (finer-grained ratio) at the cost of more
# gRPC traffic. Typical: 10.
UPTIME_CHECK_INTERVAL_MINUTES: int = 10

# Length of the rolling window used to compute a peer's failure
# ratio. Counters (recent_uptime_checks, recent_failed_uptime_checks)
# reset to zero when current_window_started_at is older than this.
# Effect: a peer that was bad a year ago but has been perfect for the
# last 6 months earns automatic forgiveness — the old data is
# discarded. Typical: 180.
UPTIME_ROLLING_WINDOW_DAYS: int = 180

# Minimum number of days a peer must have been observed in the
# current window before the failure-ratio gate can fire. Protects
# against false-positives on peers that just got added or just had
# their window reset. At the default 10-min cadence, 90 days = ~13k
# samples, which makes a 2-day outage (~288 failures) ~2.2% of the
# window — well under the 5% threshold. So a single 1-2 day blip
# can't trigger blacklisting; only sustained unreliability does.
# Typical: 90.
UPTIME_MIN_OBSERVATION_DAYS: int = 90

# Fraction of failed uptime checks above which a peer is flagged as
# unreliable (HIGH_FAILURE_RATIO). 0.05 = 5%. Applied only after the
# UPTIME_MIN_OBSERVATION_DAYS warm-up has elapsed, so transient
# 1-2 day outages can't trip it. A peer chronically flaky at this
# rate over 90+ days is genuinely unreliable. Typical: 0.05.
UPTIME_MAX_FAILURE_RATIO: float = 0.05

# A peer whose last_seen_online is older than this many days is
# flagged as LONG_OUTAGE — they're not just having a bad day, they
# appear to have gone away. Replaces the legacy 48-hour
# OFFLINE_RECENTLY check, which would false-positive on routine
# maintenance windows. Typical: 14.
UPTIME_LONG_OUTAGE_DAYS: int = 14

# Minimum age (days) a candidate Lightning node must have been
# operational. Two years (730 days) is the operator-chosen "stable
# enough" threshold — beyond this, additional age stops correlating
# with reliability and we order purely by fee rate. Avoids fly-by-
# night nodes. Typical: 730.
NODE_CRITERIA_MINIMUM_AGE: int = 730

# Maximum outbound fee rate (parts-per-million) a candidate node may
# advertise. Computed as the median fee_rate_milli_msat across all the
# node's announced (and enabled) channel policies. 10_000 ppm = 1%.
# Nodes whose median outbound fee exceeds this are rejected — both
# because routing through them would be expensive AND because high
# fees usually correlate with low remaining outbound liquidity (nodes
# raise fees to discourage further depletion). Typical: 10_000.
NODE_CRITERIA_MAX_FEE_RATE_PPM: int = 10_000

# Multiplier applied to LSP_CHANNEL_SIZE_SAT to compute the minimum
# total announced capacity a node must have. Default 10 means a 150k
# channel size requires the candidate's total capacity to be ≥1.5M
# sat across all its channels. Acts as a proxy for "does this node
# have enough outbound liquidity to immediately drain a channel we
# open to it?". Channel balances are private — we can't query
# outbound directly — so this is the best pre-open heuristic.
# Typical: 10 (strict).
NODE_CRITERIA_OUTBOUND_CAPACITY_MULTIPLIER: int = 10


# Smallest liquidity request to send to an LSP. Below this the LSP's
# minimum-fee structure makes the request uneconomical. Legacy knob;
# the LSP-funded path uses LSP_CHANNEL_SIZE_SAT instead.
MIN_INBOUND_LIQUIDITY_REQUEST_AMOUNT: int = 50_000

# Don't move less than this from on-chain to LN when rebalancing.
# Legacy AUTOMATIC_CHANNEL_CREATION knob.
MIN_ONCHAIN_TO_LN_MOVEMENT: int = 20_000

# Initial channel size for the first channel opened on a fresh wallet.
# Used in the legacy automatic-channel-open path.
INITIAL_CHANNEL_SIZE: int = 20_000

# Target inbound liquidity to request per channel-open in the legacy
# automatic-channel-open path. LSP path uses LSP_CHANNEL_SIZE_SAT instead.
TARGET_INBOUND_LIQUIDITY: int = 500_000


# =============================================================================
# === Override resolution ===
# =============================================================================
#
# Precedence (highest wins): plugin UI > environment variables >
# user_config.py > config.py defaults above. Plugin UI overrides are
# applied via the settings_bridge module after import; env vars and
# user_config.py are resolved here at import time.

if os.path.exists("user_config.py"):
    from user_config import *  # noqa: F401,F403

# Prefix every env-var lookup with this so we can't accidentally pick
# up unrelated env vars set by other software in the operator's shell
# (e.g. `STORE_NAME`, `LOG_LEVEL`, `DEBUG_MODE` are GENERIC names that
# system tools or other apps might own). Matches the convention used
# everywhere else in the codebase for our explicit env vars
# (LIQUIDITYHELPER_DB_PATH, LIQUIDITYHELPER_NODE_DB_PATH,
# LIQUIDITYHELPER_LOG_DIR, etc.).
# Note: the loop also iterates over module-level imports brought in via
# `from typing import ...` and helper imports; a bare env var collision
# with one of those names will emit the same migration warning even
# though it's not a real setting.
ENV_PREFIX = "LIQUIDITYHELPER_"

# Env-var override loop. For each UPPER_SNAKE_CASE local defined above:
#   - if LIQUIDITYHELPER_<NAME> is set, replace the local default with
#     the parsed env-var value.
#   - else if the BARE <NAME> is set in the environment (possibly an
#     operator who hasn't updated to the prefixed form, possibly a
#     name collision with another app), print a one-shot stderr
#     warning so they notice the override didn't take effect.
# Supports basic type inference for the prefixed form:
# "None"/"True"/"False" (case-insensitive), integers, floats, otherwise
# string.
import sys as _sys

for entry in list(locals().items()):
    name = entry[0]
    value = entry[1]
    if name.startswith("_"):
        continue
    if name in {"environ", "ENV_PREFIX"}:
        continue
    prefixed = f"{ENV_PREFIX}{name}"
    if prefixed in environ:
        environ_var = environ.get(prefixed)
        if environ_var.upper() == "NONE":
            locals()[name] = None
            continue
        if environ_var.upper() == "TRUE":
            locals()[name] = True
            continue
        if environ_var.upper() == "FALSE":
            locals()[name] = False
            continue
        if environ_var != "":
            if is_integer(environ_var):
                locals()[name] = int(environ_var)
            elif is_float(environ_var):
                locals()[name] = float(environ_var)
            else:
                locals()[name] = environ_var
            continue
    elif name in environ:
        # Bare-name env var is set but no longer honored. Most likely
        # an operator who hasn't migrated to the prefixed form; could
        # also be a coincidental collision with another app — both
        # cases want the same fix (use the prefixed form, or unset).
        print(
            f"WARNING: env var {name!r} is set but ignored — use "
            f"{prefixed!r} to override the {name} config setting.",
            file=_sys.stderr,
        )
