# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: debug.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'debug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x62ug.proto\x12\x07looprpc\"\x16\n\x14\x46orceAutoLoopRequest\"\x17\n\x15\x46orceAutoLoopResponse2W\n\x05\x44\x65\x62ug\x12N\n\rForceAutoLoop\x12\x1d.looprpc.ForceAutoLoopRequest\x1a\x1e.looprpc.ForceAutoLoopResponseB\'Z%github.com/lightninglabs/loop/looprpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/lightninglabs/loop/looprpc'
  _globals['_FORCEAUTOLOOPREQUEST']._serialized_start=24
  _globals['_FORCEAUTOLOOPREQUEST']._serialized_end=46
  _globals['_FORCEAUTOLOOPRESPONSE']._serialized_start=48
  _globals['_FORCEAUTOLOOPRESPONSE']._serialized_end=71
  _globals['_DEBUG']._serialized_start=73
  _globals['_DEBUG']._serialized_end=160
# @@protoc_insertion_point(module_scope)
